COMPILER = g++
FLAGS = -std=c++11 -pedantic -Wall -Wextra

TARGET = rozklad_liczb

make:
		$(COMPILER) main.cpp $(FLAGS) -o $(TARGET)
			$(RM) main.o
clean:
		$(RM) $(TARGET)
			$(RM) $(OBJ)
.PHONY: depend clean
